#!/usr/bin/env python3
"""Full new-module tests with explicit Lua 5.4 doubles, not native GMod tests."""
from pathlib import Path
import argparse,json,sys
from lua_support import Lua,normalize

def main(root:Path,output:Path)->int:
    root=root.resolve();here=Path(__file__).resolve().parent;lua=Lua();results=[]
    def src(path,start=None,stop=None):
        s=(root/path).read_text()
        if start:s=s[s.index(start):]
        if stop:s=s[:s.index(stop)]
        return 'do\nlocal function module_chunk()\n'+normalize(s)+'\nend\nmodule_chunk()\nend\n'
    base=(here/'stubs.lua').read_text()+(here/'custom_stubs.lua').read_text()
    base+=src('lua/seamless_portals/core.lua')+src('lua/seamless_portals/features.lua')+src('lua/seamless_portals/aperture.lua')
    base+=src('lua/entities/seamless_portal/sh_init.lua','SeamlessPortals.TransformPortal = function','-- Only render the portals')
    mods={name:src('lua/seamless_portals/'+name+'.lua') for name in ['traces','bullets','holding','transport','funneling','sound','tool_features','custom_defaults']}
    carry=mods['holding']+mods['transport']
    def test(id,title,code,modules='',category='custom behavior'):
        try:
            observed=lua.check(base+modules+code+'\nreturn "assertions passed"',True,id)
            assert observed == 'assertions passed', 'Test assertions were bypassed by an early chunk return'
            status='PASS'
        except Exception as exc:status='FAIL';observed=str(exc)
        results.append(dict(id=id,title=title,status=status,observed=observed,kind='full module/excerpt with explicit API doubles',category=category))
    test('C-T01','Custom user-facing defaults, including optional funnel', '''local a,b=pair();for _,key in ipairs({'props','players','sound','damage'}) do assert(SeamlessPortals.FeatureEnabled(a,key)) end;assert(not SeamlessPortals.FeatureEnabled(a,'funnel'))''')
    test('C-T02','Disabling props does not disable players and is mirrored to dupe data', '''local a,b=pair();assert(SeamlessPortals.SetFeature(a,'props',false));assert(not SeamlessPortals.LinkAllows(a,b,'props'));assert(SeamlessPortals.LinkAllows(a,b,'players'));assert(a.dupe.props==false);assert(not SeamlessPortals.SetFeature(a,'sound','1'))''')
    test('C-T03','Callback argument order and entry/exit outputs', '''local a,b=pair();local p=player();local seen={};function a:RunPlyUsageCallbacks(ply,phase,other) assert(ply==p and phase=='entry' and other==b);seen.a=true end;function b:RunPlyUsageCallbacks(ply,phase,other) assert(ply==p and phase=='exit' and other==a);seen.b=true end;SeamlessPortals.NotifyTraversal(p,a,b,'player');assert(seen.a and seen.b and a.outputs[1][2]==p and b.outputs[1][1]=='OnTeleportTo')''')
    test('C-T04','Failing entry callback does not suppress exit callback', '''local a,b=pair();local called=false;function a:RunPlyUsageCallbacks() error('extension') end;function b:RunPlyUsageCallbacks() called=true end;SeamlessPortals.NotifyTraversal(player(),a,b,'player');assert(called and LAST_ERROR)''')
    test('C-T05','All supported polygons have clockwise area and contain center', '''for n=3,100 do local p=portal(Vector(143,91,8),n);local v=SeamlessPortals.ApertureVertices(p);local area=0;for i,a in ipairs(v) do local b=v[i%#v+1];area=area+a.x*b.y-b.x*a.y end;assert(area<0 and #v==n and SeamlessPortals.InApertureLocal(p,Vector()));assert(not SeamlessPortals.InApertureLocal(p,Vector(1000,0,0))) end''')
    test('C-T06','Border pieces conserve rectangle-minus-aperture area for sides 3..100', '''local function area(poly) local sum=0;for i,a in ipairs(poly) do local b=poly[i%#poly+1];sum=sum+a.x*b.y-b.x*a.y end;return math.abs(sum)/2 end;for n=3,100 do local p=portal(Vector(143,91,8),n);local lo,hi=SeamlessPortals.GetApertureBounds(p.size,n);local total=area(SeamlessPortals.ApertureVertices(p));for _,piece in ipairs(SeamlessPortals.ApertureBorderPieces(p)) do total=total+area(piece) end;near(total,(hi.x-lo.x)*(hi.y-lo.y),1e-5) end''')
    test('C-T07','Closest point stays within every polygon including rounded portals', '''for n=3,100 do local p=portal(nil,n);for _,v in ipairs({Vector(100,150,25),Vector(-150,-100,-5),Vector()}) do local q=SeamlessPortals.ClosestAperturePoint(p,v);assert(SeamlessPortals.InAperture(p,q));near(q.z,0) end end''')
    test('C-T08','Trace traversal refuses backside and aperture mismatch', '''local a,b=pair();local tr={Hit=true,HitPos=Vector(),HitNormal=a:GetUp(),Entity=a};assert(SeamlessPortals.CanCrossTrace(tr,Vector(0,0,10),Vector(0,0,-1)));assert(not SeamlessPortals.CanCrossTrace(tr,Vector(0,0,-10),Vector(0,0,1)));b.sides=3;tr.HitPos=Vector(45,45,0);assert(not SeamlessPortals.CanCrossTrace(tr,Vector(45,45,10),Vector(0,0,-1)))''',mods['traces'])
    tracefixture='''local a,b=pair();local hits=0;local raw=function(d) hits=hits+1;if hits==1 then return {Hit=true,StartPos=d.start,HitPos=Vector(),HitNormal=a:GetUp(),Entity=a,Fraction=.1,StartSolid=false,AllSolid=false} end;return {Hit=false,StartPos=d.start,HitPos=d.endpos,HitNormal=Vector(),Entity=NULL,Fraction=1,StartSolid=false,AllSolid=false} end;'''
    test('C-T09','Trace distance accounting, copy ownership and world continuation',tracefixture+'''local d={start=Vector(0,0,10),endpos=Vector(0,0,-90),output={SeamlessSegments='stale'}};local t=SeamlessPortals.TracePortalLine(d,raw);assert(t==d.output and #t.SeamlessSegments==2 and hits==2);near(t.Fraction,1);nearvec(d.endpos,Vector(0,0,-90));nearvec(t.HitPos,Vector(200,0,90))''',mods['traces'])
    test('C-T10','Maximum hop count zero does not traverse',tracefixture+'''local t=SeamlessPortals.TracePortalLine({start=Vector(0,0,10),endpos=Vector(0,0,-90),SeamlessMaxHops=0},raw);assert(hits==1 and t.Entity==a and not t.SeamlessSegments)''',mods['traces'])
    test('C-T11','Trace wrapper restores identity and avoids stomping later wrappers', '''local a,b=pair();local old=util.TraceLine;SeamlessPortals.UpdateTraceOwnership();local own=util.TraceLine;assert(own~=old);local outer=function(d) return own(d) end;util.TraceLine=outer;a.exit=NULL;b.exit=NULL;SeamlessPortals.LinkedRegistryDirty=true;SeamlessPortals.UpdateTraceOwnership();assert(util.TraceLine==outer);a.exit=b;SeamlessPortals.LinkedRegistryDirty=true;SeamlessPortals.UpdateTraceOwnership();assert(util.TraceLine==outer)''',mods['traces'])
    test('C-T12','Trace exception releases reentrancy guard', '''local a,b=pair();util.TraceLine=function() error('raw') end;SeamlessPortals.UpdateTraceOwnership();assert(not pcall(util.TraceLine,{start=Vector(),endpos=Vector(0,0,-10)}));assert(not SeamlessPortals.TraceOwnership.busy)''',mods['traces'])
    bulletfixture='''local a,b=pair();local shooter=prop();local fired={};function shooter:FireBullets(data) fired[#fired+1]=data end;local data={Src=Vector(0,0,10),Dir=Vector(0,0,-1),Distance=100,Damage=0,Num=8,Spread=Vector(.1,.1,0),IgnoreEntity=shooter};local damage=DamageInfo();local tr={Hit=true,StartPos=data.Src,HitPos=Vector(),HitNormal=a:GetUp(),Entity=a};'''
    test('C-T13','Actual spread ray transformed; original pellet count not repeated',bulletfixture+'''assert(hook.Run('EntityFireBullets',shooter,data));tr.HitPos=Vector(1,0,0);data.Callback(shooter,tr,damage);assert(#fired==1 and fired[1].Num==1 and fired[1].Spread:IsZero());nearvec(fired[1].Dir,Vector(1,0,10):GetNormalized());assert(data.Num==8 and data.IgnoreEntity==shooter and fired[1].IgnoreEntity==nil and fired[1].Damage==0)''',mods['traces']+mods['bullets'])
    test('C-T14','Per-portal damage disable leaves original callback and no relay',bulletfixture+'''SeamlessPortals.SetFeature(a,'damage',false);local called=0;data.Callback=function() called=called+1;return {damage=false} end;hook.Run('EntityFireBullets',shooter,data);assert(data.Callback(shooter,tr,damage).damage==false and called==1 and #fired==0)''',mods['traces']+mods['bullets'])
    test('C-T15','Bullet recursion depth resets on injected FireBullets failure',bulletfixture+'''function shooter:FireBullets() error('native stub failure') end;hook.Run('EntityFireBullets',shooter,data);assert(data.Callback(shooter,tr,damage).damage==false and SeamlessPortals.BulletContinuationDepth==0 and LAST_ERROR)''',mods['traces']+mods['bullets'])
    test('C-T16','Two traversals rotate force exactly twice; final callback once',bulletfixture+'''local c,d=portal(),portal();c.pos=Vector(200,0,20);c.up=Vector(0,0,-1);c.right=Vector(0,1,0);d.pos=Vector(400,0,0);c.exit=d;d.exit=c;local final=0;data.Callback=function(_,_,info) final=final+1;nearvec(info:GetDamageForce(),Vector(0,0,10)) end;hook.Run('EntityFireBullets',shooter,data);data.Callback(shooter,tr,damage);local next=fired[1];local second=DamageInfo();next.Callback(shooter,{Hit=true,StartPos=next.Src,HitPos=c.pos,HitNormal=c.up,Entity=c},second);assert(#fired==2);fired[2].Callback(shooter,{Hit=true,StartPos=fired[2].Src,HitPos=Vector(400,0,10),HitNormal=Vector(),Entity=prop()},DamageInfo());assert(final==1)''',mods['traces']+mods['bullets'])
    test('C-T17','Eight-hop budget terminates without another native shot',bulletfixture+'''local fn=SeamlessPortals.PortalBulletCallback(shooter,data,nil,8);assert(fn(shooter,tr,damage).damage==false and #fired==0)''',mods['traces']+mods['bullets'])
    test('C-T18','Invalid hull sizes are not installed into bullet callback',bulletfixture+'''for _,v in ipairs({-1,math.huge,0/0}) do data.HullSize=v;data.Callback=nil;assert(hook.Run('EntityFireBullets',shooter,data)==nil and data.Callback==nil) end''',mods['traces']+mods['bullets'])
    test('C-T19','Only confirmed pickups establish carry records', '''local p,e=player(),prop();hook.Run('PhysgunPickup',p,e);assert(not SeamlessPortals.GetHeldRecord(p));e.holding=true;hook.Run('OnPhysgunPickup',p,e);assert(SeamlessPortals.GetHeldRecord(p).kind=='physgun' and SeamlessPortals.HeldBy(e)==p);hook.Run('PhysgunDrop',p,e);assert(not SeamlessPortals.GetHeldRecord(p))''',carry)
    test('C-T20','E pickup/drop/death cleanup uses confirmed native hooks', '''local p,e=player(),prop();e.holding=true;hook.Run('OnPlayerPhysicsPickup',p,e);assert(SeamlessPortals.GetHeldRecord(p).kind=='use');hook.Run('PlayerDeath',p);assert(not SeamlessPortals.GetHeldRecord(p) and not IsValid(p:GetNWEntity('seamless_portals_held')))''',carry)
    test('C-T21','Competing controller ownership fails closed without choosing a player', '''local p,q,e=player(),player(),prop();e.holding=true;SeamlessPortals.RecordHold(p,e,'physgun');SeamlessPortals.RecordHold(q,e,'physgun');assert(not SeamlessPortals.HeldBy(e));assert(not SeamlessPortals.CollectTransportGroup(e,p))''',carry)
    test('C-T22','Stale native hold records expire after the pickup grace tick', '''local p,e=player(),prop();SeamlessPortals.RecordHold(p,e,'use');assert(SeamlessPortals.GetHeldRecord(p));TICK=TICK+2;assert(not SeamlessPortals.GetHeldRecord(p))''',carry)
    groupfixture='''local a,b=pair();local e,f=prop(Vector(0,0,-3),2),prop(Vector(6,0,-3));local group={[e]=e,[f]=f};e.group=group;f.group=group;'''
    test('C-T23','Rigid assembly transport preserves pair distance and each PhysObj identity',groupfixture+'''local plan,why=SeamlessPortals.PlanTransport(e,a,b);assert(plan,why);local bodies={e.bodies[1],e.bodies[2],f.bodies[1]};assert(SeamlessPortals.CommitTransport(plan));near(e.pos:Distance(f.pos),6);assert(e.bodies[1]==bodies[1] and e.bodies[2]==bodies[2] and f.bodies[1]==bodies[3]);nearvec(e.bodies[1].vel,Vector(1,-2,-3));nearvec(e.bodies[1].angular,Vector(4,5,6));assert(e.bodies[1].motion_writes==0 and e.group==group)''',carry)
    test('C-T24','Held E/physgun commits never call drop, physics rebuild or motion toggle', '''for _,kind in ipairs({'use','physgun'}) do local a,b=pair();local p,e=player(),prop(Vector(0,0,-3));e.holding=true;SeamlessPortals.RecordHold(p,e,kind);local phys=e.bodies[1];local plan,why=SeamlessPortals.PlanTransport(e,a,b,p,Vector(),Vector(200,0,4));assert(plan,why);assert(SeamlessPortals.CommitTransport(plan));assert(SeamlessPortals.GetHeldRecord(p).entity==e and e.holding and e.bodies[1]==phys and phys.motion_writes==0) end''',carry)
    test('C-T25','World anchored weld refused before any write',groupfixture+'''e.constraints={{Type='Weld',Entity={{World=true,Entity=WORLD}}}};local plan,reason=SeamlessPortals.PlanTransport(e,a,b);assert(not plan and reason=='world_anchored_constraint');nearvec(e.pos,Vector(0,0,-3))''',carry)
    test('C-T26','World NoCollide is not mistaken for a physical anchor',groupfixture+'''e.constraints={{Type='NoCollide',Entity={{World=true,Entity=WORLD}}}};assert(SeamlessPortals.PlanTransport(e,a,b))''',carry)
    test('C-T27','Blocked assembly destination rejects entire group without mutation',groupfixture+'''local n=0;util.TraceHull=function() n=n+1;return {Hit=n==2} end;local plan,reason=SeamlessPortals.PlanTransport(e,a,b);assert(not plan and reason=='exit_obstructed');nearvec(e.pos,Vector(0,0,-3));nearvec(f.pos,Vector(6,0,-3))''',carry)
    test('C-T28','Injected mid-commit failure rolls surviving bodies back',groupfixture+'''local plan=assert(SeamlessPortals.PlanTransport(e,a,b));f.bodies[1].fail_once=true;local ok=SeamlessPortals.CommitTransport(plan);assert(not ok);nearvec(e.pos,Vector(0,0,-3));nearvec(f.pos,Vector(6,0,-3));nearvec(e.bodies[1].pos,Vector(0,0,-3));nearvec(e.bodies[1].vel,Vector(1,2,3))''',carry)
    test('C-T29','Graph changes between plan and commit reject before mutation',groupfixture+'''local plan=assert(SeamlessPortals.PlanTransport(e,a,b));e.group={[e]=e};local ok,reason=SeamlessPortals.CommitTransport(plan);assert(not ok and reason=='constraint_graph_changed');nearvec(e.pos,Vector(0,0,-3))''',carry)
    test('C-T30','Replaced PhysObj invalidates a pending transaction',groupfixture+'''local plan=assert(SeamlessPortals.PlanTransport(e,a,b));e.bodies[1]=physics(e.pos);local ok,reason=SeamlessPortals.CommitTransport(plan);assert(not ok and reason=='physics_replaced')''',carry)
    test('C-T31','Feature disabled after planning prevents commit',groupfixture+'''local plan=assert(SeamlessPortals.PlanTransport(e,a,b));SeamlessPortals.SetFeature(a,'props',false);local ok,reason=SeamlessPortals.CommitTransport(plan);assert(not ok and reason=='portal_changed')''',carry)
    test('C-T32','Admission resolves unique holder from another member, transfer does not',groupfixture+'''local p=player();f.holding=true;SeamlessPortals.RecordHold(p,f,'physgun');assert(SeamlessPortals.CollectTransportGroup(e,nil,true));assert(not SeamlessPortals.CollectTransportGroup(e,nil));assert(SeamlessPortals.PlanTransport(e,a,b,p))''',carry)
    test('C-T33','Large prop rejected against actual rounded aperture, not bounding box', '''local a,b=pair(50);local e=prop(Vector(47,47,-3));e.lo=Vector(-4,-4,-1);e.hi=Vector(4,4,1);local plan,reason=SeamlessPortals.PlanTransport(e,a,b);assert(not plan and reason=='group_does_not_fit_entry')''',carry)
    test('C-T34','Differently sized pair keeps assembly dimensions rather than stretching welds',groupfixture+'''b.size=Vector(200,200,8);local plan=assert(SeamlessPortals.PlanTransport(e,a,b));assert(SeamlessPortals.CommitTransport(plan));near(e.pos:Distance(f.pos),6)''',carry)
    test('C-T35','Mirror and nonreciprocal physical group transfers reject explicitly', '''local a,b=pair();local e=prop(Vector(0,0,-3));a.exit=a;assert(not SeamlessPortals.PlanTransport(e,a,a));a.exit=b;b.exit=NULL;local plan,why=SeamlessPortals.PlanTransport(e,a,b);assert(not plan and why=='nonreciprocal_physical_pair')''',carry)
    test('C-T36','Blocked carry cancels only inward velocity and retains holder record', '''local a,b=pair();local p,e=player(),prop();e.holding=true;SeamlessPortals.RecordHold(p,e,'use');local mv=move(Vector(0,0,-1),Vector(8,4,-20));assert(SeamlessPortals.BlockHeldTraversal(p,mv,a,'test'));nearvec(mv.vel,Vector(8,4,0));assert(mv.pos.z>=0.5 and SeamlessPortals.GetHeldRecord(p).entity==e)''',carry)
    test('C-T37','Retired clones do not execute another physics-coupling tick',groupfixture+'''local clone=prop();e.SEAMLESS_PORTALS_CLONE=clone;local plan=assert(SeamlessPortals.PlanTransport(e,a,b));assert(SeamlessPortals.CommitTransport(plan));assert(clone.SEAMLESS_PORTALS_RETIRED and clone.notsolid and clone.nodraw)''',carry)
    test('C-T38','Funneling time-normalization composes across tick rates', '''local a=SeamlessPortals.FunnelAlpha(1/66,false);near(a,.05);near(1-(1-a)^66,1-(1-SeamlessPortals.FunnelAlpha(1/100,false))^100,1e-8);assert(SeamlessPortals.FunnelAlpha(1/66,true)<a)''',mods['funneling'])
    test('C-T39','Funneling preserves speed and lateral movement weakens correction', '''local a,b=pair();SeamlessPortals.SetFeature(a,'funnel',true);local p=player();local one=move(Vector(10,0,100),Vector(0,0,-500));local two=move(Vector(10,0,100),Vector(0,0,-500),100);SeamlessPortals.ApplyFunneling(p,one,1/66);SeamlessPortals.ApplyFunneling(p,two,1/66);near(one.vel:Length(),500);near(two.vel:Length(),500);assert(one.vel.x<two.vel.x and two.vel.x<0)''',mods['funneling'])
    test('C-T40','Funneling disabled by default and absent below run speed', '''local a,b=pair();local p=player();local mv=move(Vector(10,0,100),Vector(0,0,-500));SeamlessPortals.ApplyFunneling(p,mv,1/66);nearvec(mv.vel,Vector(0,0,-500));SeamlessPortals.SetFeature(a,'funnel',true);mv.vel=Vector(0,0,-100);SeamlessPortals.ApplyFunneling(p,mv,1/66);nearvec(mv.vel,Vector(0,0,-100))''',mods['funneling'])
    test('C-T41','Sound relays to exit PAS without moving source', '''local a,b=pair();local e=prop(Vector(0,0,10));hook.Run('EntityEmitSound',{Entity=e,SoundName='test.wav',Pos=e.pos,Volume=.5,SoundLevel=75});assert(#net.messages>=1);nearvec(e.pos,Vector(0,0,10));nearvec(net.messages[1].filter.pas,Vector(200,0,4))''',mods['sound'])
    test('C-T42','Sound recursion from an extension veto hook is bounded', '''local a,b=pair();local calls=0;hook.Add('SeamlessPortalsAllowSoundRelay','recursive',function(t) calls=calls+1;hook.Run('EntityEmitSound',t) end);hook.Run('EntityEmitSound',{SoundName='test.wav',Pos=Vector(0,0,10)});assert(calls==1 and #net.messages==1)''',mods['sound'])
    test('C-T43','Sound opt-out and per-tick network budget', '''local a,b=pair();local t={SoundName='test.wav',Pos=Vector(0,0,10)};SeamlessPortals.SetFeature(a,'sound',false);hook.Run('EntityEmitSound',t);assert(#net.messages==0);SeamlessPortals.SetFeature(a,'sound',true);for i=1,100 do hook.Run('EntityEmitSound',t) end;assert(#net.messages==64);TICK=TICK+1;hook.Run('EntityEmitSound',t);assert(#net.messages==65)''',mods['sound'])
    client_sound='CLIENT=true;SERVER=false;\n'+mods['sound']
    soundfixture='''local a,b=pair();local path={entry=a,exit=b,pos=Vector(200,0,-10)};local t={SoundName='test.wav',Channel=1,SeamlessRealm='server'};'''
    test('C-T44','Client emitter lifecycle: expiration, source untouched and portal removal',soundfixture+'''SeamlessPortals.PlayPortalSound(path,42,t);assert(#CLIENT_EMITTERS==1);local e=CLIENT_EMITTERS[1];assert(e.emitted==1);NOW=NOW+3;hook.Run('Think');assert(not IsValid(e) and not next(SeamlessPortals.SoundEmitters))''',client_sound)
    test('C-T45','Explicit stop and same-channel replacement stop owned emitters',soundfixture+'''SeamlessPortals.PlayPortalSound(path,42,t);local first=CLIENT_EMITTERS[1];t.SoundName='second.wav';SeamlessPortals.PlayPortalSound(path,42,t);assert(not IsValid(first));t.Flags=4;SeamlessPortals.PlayPortalSound(path,42,t);assert(not next(SeamlessPortals.SoundEmitters))''',client_sound)
    test('C-T46','Server/client duplicate suppression does not erase same-realm repetitions',soundfixture+'''t.Channel=CHAN_AUTO;SeamlessPortals.PlayPortalSound(path,42,t);t.SeamlessRealm='client';SeamlessPortals.PlayPortalSound(path,42,t);assert(#CLIENT_EMITTERS==1);t.SeamlessRealm='server';SeamlessPortals.PlayPortalSound(path,42,t);assert(#CLIENT_EMITTERS==2)''',client_sound)
    test('C-T47','Server relay disable also retires client emitters',soundfixture+'''SeamlessPortals.PlayPortalSound(path,42,t);CVARS.seamless_portals_soundrelay_server.value=0;hook.Run('Think');assert(not next(SeamlessPortals.SoundEmitters))''',client_sound)
    test('C-T48','Custom defaults migrate archived RC1 opt-outs exactly once', '''CVARS.seamless_portals_soundrelay_server.value=0;CVARS.seamless_portals_global_trace.value=0;'''+mods['custom_defaults']+'''assert(CVARS.seamless_portals_soundrelay_server.value==1 and CVARS.seamless_portals_global_trace.value==1);CVARS.seamless_portals_soundrelay_server.value=0;'''+mods['custom_defaults']+'''assert(CVARS.seamless_portals_soundrelay_server.value==0)''',mods['traces']+mods['bullets']+mods['sound'])
    test('C-T49','Portal editing retargets only after CanTool approves entry', '''local a,b=pair();local p=player();local tool={GetOwner=function() return p end,GetWeapon=function() return NULL end,Mode='portal_behavior_tool'};util.GetPlayerTrace=function() return {} end;SeamlessPortals.TraceLine=function() return {Hit=true,Entity=a} end;local allowed=false;gamemode={Call=function(name,who,tr,mode,tool,button) assert(name=='CanTool' and who==p and tr.Entity==a and button==1);return allowed end};assert(not SeamlessPortals.RawToolTrace(tool,{SeamlessSegments={}},1));allowed=true;assert(SeamlessPortals.RawToolTrace(tool,{SeamlessSegments={}},1).Entity==a)''',mods['tool_features'])
    test('C-T50','Default creation options preserve sound, damage and separate prop switch', '''local a,b=pair();local p=player();function p:GetInfoNum(name,fallback) if name=='seamless_portals_feature_props' then return 0 end return fallback end;assert(SeamlessPortals.ApplyToolFeatures(a,p));assert(not SeamlessPortals.FeatureEnabled(a,'props'));assert(SeamlessPortals.FeatureEnabled(a,'players') and SeamlessPortals.FeatureEnabled(a,'sound') and SeamlessPortals.FeatureEnabled(a,'damage'))''',mods['tool_features'])
    movement=carry+mods['funneling']+src('lua/autorun/sh_player_teleport.lua')
    movefixture='''local a,b=pair();local p,e=player(),prop(Vector(0,0,-3));local mv=move(Vector(0,0,-5.9),Vector(0,0,-100));SeamlessPortals.TraceLine=function(d) return {Hit=true,Entity=a,HitNormal=a.up,HitPos=Vector(),StartSolid=false} end;'''
    test('C-T51','Actual Move hook commits player and held E prop together',movefixture+'''e.holding=true;hook.Run('OnPlayerPhysicsPickup',p,e);local phys=e.bodies[1];assert(hook.Run('Move',p,mv)==true);assert(mv.pos.x==200 and mv.vel.z>0 and e.pos.x==200);assert(e.holding and e.bodies[1]==phys and phys.motion_writes==0);assert(SeamlessPortals.GetHeldRecord(p).entity==e and p.eyeang and #a.outputs==2);assert(net.messages[1].name=='SEAMLESS_PORTALS_TRANSITION_ACK_V2')''',movement)
    test('C-T52','Actual Move hook carries physgun assembly and notifies every member',movefixture+'''local f=prop(Vector(6,0,-3));e.group={[e]=e,[f]=f};f.group=e.group;e.holding=true;hook.Run('OnPhysgunPickup',p,e);assert(hook.Run('Move',p,mv)==true);near(e.pos:Distance(f.pos),6);assert(f.pos.x==206 and #a.outputs==3 and SeamlessPortals.GetHeldRecord(p).kind=='physgun')''',movement)
    test('C-T53','Actual Move hook blocks disabled prop transfer without dropping or teleporting player',movefixture+'''e.holding=true;hook.Run('OnPlayerPhysicsPickup',p,e);SeamlessPortals.SetFeature(a,'props',false);assert(hook.Run('Move',p,mv)==true);assert(mv.pos.x==0 and e.pos.x==0 and e.holding and #net.messages==0);assert(p.SEAMLESS_PORTALS_TRANSPORT_BLOCKED=='held_props_disabled_or_mirror')''',movement)
    test('C-T54','Actual Move hook ignores nonportal hits rather than invoking entity portal methods',movefixture+'''SeamlessPortals.TraceLine=function() return {Hit=true,Entity=WORLD} end;assert(hook.Run('Move',p,mv)==nil);nearvec(mv.pos,Vector(0,0,-5.9))''',movement)
    test('C-T55','Actual Move hook rejects blocked exit as one held transaction',movefixture+'''e.holding=true;hook.Run('OnPhysgunPickup',p,e);util.TraceHull=function(data) return {Hit=data.mask==MASK_SOLID,StartSolid=false,Fraction=1} end;assert(hook.Run('Move',p,mv)==true);assert(mv.pos.x==0 and e.pos.x==0 and e.holding and p.SEAMLESS_PORTALS_TRANSPORT_BLOCKED=='exit_obstructed')''',movement)
    test('C-T56','Player-only self-link still transitions and publishes absolute mirror state',movefixture+'''a.exit=a;assert(hook.Run('Move',p,mv)==true);assert(p.SEAMLESS_PORTALS_MIRRORED==true and mv.vel.z>0 and #a.outputs==2)''',movement)
    skyfixture='''CLIENT=true;SERVER=false;color_white={};CreateConVar('sv_skyname','test');local planes,clipping,override=0,true,false;function Material() return {IsError=function() return false end} end;render={EnableClipping=function(v) local old=clipping;clipping=v;return old end,OverrideDepthEnable=function(v) override=v end,SetMaterial=function() end,DrawQuadEasy=function() planes=planes+1 end};'''
    # This fixture needs locals shared with assertions, so use plain source inside
    # the test body after the fixture, not before it in the module list.
    sky=src('lua/seamless_portals/skybox.lua')
    test('C-T57','Six-face fallback balances owned depth/clipping state',skyfixture+sky+'''SeamlessPortals.DrawFallbackSky(Vector());assert(planes==6 and clipping and not override)''')
    test('C-T58','Sky fallback restores state after injected render error',skyfixture+sky+'''render.DrawQuadEasy=function() error('draw failure') end;SeamlessPortals.DrawFallbackSky(Vector());assert(clipping and not override and LAST_ERROR)''')
    test('C-T59','Sky fallback only runs for a missing sky in a portal view',skyfixture+sky+'''util.IsSkyboxVisibleFromPoint=function() return false end;SeamlessPortals.Rendering=true;SeamlessPortals.PortalVirtualEye=Vector();hook.Run('PostDrawTranslucentRenderables',true,false);assert(planes==0);hook.Run('PostDrawTranslucentRenderables',false,false);assert(planes==6 and SeamlessPortals.PortalSkySeen);hook.Run('PostDrawTranslucentRenderables',false,false);assert(planes==6)''')
    test('C-T60','Group and physics body budgets reject unsupported graphs','''local a,b=pair();local e=prop();e.group={[e]=e};for i=1,64 do local f=prop();e.group[f]=f end;local plan,why=SeamlessPortals.PlanTransport(e,a,b);assert(not plan and why=='group_entity_budget');e.group=nil;e=prop(Vector(),33);plan,why=SeamlessPortals.PlanTransport(e,a,b);assert(not plan and why=='unsupported_physics_count')''',carry)
    report={'native_gmod_tested':False,'limits':'No engine physics/controller/network/render execution. Mocks prove the Lua calls and invariants only. Native carry retention remains an acceptance requirement.','tests':results,'passed':sum(t['status']=='PASS' for t in results),'failed':sum(t['status']!='PASS' for t in results)}
    output.parent.mkdir(parents=True,exist_ok=True);output.write_text(json.dumps(report,indent=2)+'\n')
    for t in results:
        print(t['status'],t['id'],t['title'])
        if t['status']!='PASS': print(t['observed'])
    print(f"{report['passed']}/{len(results)} custom feature checks (not native GMod)")
    return int(bool(report['failed']))
if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('source',type=Path);p.add_argument('--output',type=Path,required=True);a=p.parse_args()
    raise SystemExit(main(a.source,a.output))
